### ISSUE TITLE
how to install labca at win10_64 with matlab2017a

### ISSUE THREAD

**Issue by hunter-asd** [till-s/epics-labca#3]
Hi till:
hope you are well

i am  new at epics,i want to intergrate labca to matlab2017a,but i can not complete the installation,could you give me a step by step instruction to follow.thanks a lot.

Looking forward to your reply

**Comment by till-s** [comment]
Hello  Hunter.
You can find detailed instructions in the manual. If you still need help after studying the manual then you need to provide more information about what exactly you were doing and what failed.
Best, Till.
